package com.system.demo.integration;

import com.system.demo.dto.RestCountriesCountryResponse;
import com.system.demo.dto.RestCountriesCurrencyInfo;
import com.system.demo.model.Country;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Flux;

import java.math.BigDecimal;
import java.util.Map;

@Slf4j
@Component
public class RestCountriesApiClient {

    private final WebClient webClient;
    private static final String BASE_URL = "https://restcountries.com/v3.1";
    private static final long MIN_POPULATION = 1_000_000L;

    public RestCountriesApiClient(WebClient.Builder webClientBuilder) {
        this.webClient = webClientBuilder.baseUrl(BASE_URL).build();
        log.info("RestCountriesApiClient initialized with base URL: {}", BASE_URL);
    }

    public Flux<Country> fetchAllCountries() {
        log.info("Fetching all countries from external API");
        return webClient.get()
                .uri("/all?fields=name,capital,region,subregion,population,area,currencies")
                .retrieve()
                .bodyToFlux(RestCountriesCountryResponse.class)
                .doOnNext(response -> log.debug("Received country: {}",
                        response.getName() != null ? response.getName().getCommon() : "unknown"))
                .map(this::mapToCountry)
                .doOnError(error -> log.error("Error fetching countries from external API", error))
                .doOnComplete(() -> log.info("Completed fetching countries from external API"));
    }


    private Country mapToCountry(RestCountriesCountryResponse response) {
        //log.debug("Mapping API response to Country entity");
        Country country = new Country();
        // ID will be generated by database
        country.setName(response.getName() != null ? response.getName().getCommon() : null);
        country.setOfficialName(response.getName() != null ? response.getName().getOfficial() : null);
        country.setCapital(response.getCapital() != null && !response.getCapital().isEmpty() ? response.getCapital().get(0) : null);
        country.setRegion(response.getRegion());
        country.setSubregion(response.getSubregion());
        country.setPopulation(response.getPopulation());
        country.setArea(response.getArea() != null ? BigDecimal.valueOf(response.getArea()) : null);

        // Extract currency code and name from nested structure
        if (response.getCurrencies() != null && !response.getCurrencies().isEmpty()) {
            Map.Entry<String, RestCountriesCurrencyInfo> firstCurrency = response.getCurrencies().entrySet().iterator().next();
            country.setCurrencyCode(firstCurrency.getKey());
            country.setCurrencyName(firstCurrency.getValue().getName());
        }

        return country;
    }
}
